/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  // Always dark — no toggle.
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002d80",
        "on-primary": "#47007c",
        "secondary-dim": "#316bf3",
        "primary-dim": "#9c48ea",
        "error": "#ff6e84",
        "tertiary-container": "#fc4563",
        "primary-fixed-dim": "#b971ff",
        "surface-container-highest": "#23262d",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#c284ff",
        "inverse-on-surface": "#53555b",
        "surface-container-high": "#1d1f26",
        "tertiary-fixed": "#ff9099",
        "surface": "#00000f",
        "on-tertiary": "#490010",
        "on-tertiary-fixed-variant": "#780021",
        "secondary-fixed-dim": "#b0c2ff",
        "on-surface": "#f0f0f8",
        "on-background": "#f0f0f8",
        "on-error": "#490013",
        "tertiary": "#ff6f7e",
        "primary": "#cc97ff",
        "secondary-fixed": "#c4d0ff",
        "on-primary-fixed": "#000000",
        "secondary-container": "#0053db",
        "surface-dim": "#00000f",
        "on-error-container": "#ffb2b9",
        "on-secondary-fixed-variant": "#0047bd",
        "inverse-primary": "#842cd3",
        "on-surface-variant": "#aaaab2",
        "surface-tint": "#cc97ff",
        "surface-bright": "#1a1a2e",
        "background": "#00000f",
        "on-primary-container": "#360061",
        "error-dim": "#d73357",
        "on-tertiary-container": "#100001",
        "on-secondary-container": "#f8f7ff",
        "error-container": "#a70138",
        "on-tertiary-fixed": "#39000b",
        "on-primary-fixed-variant": "#430076",
        "outline": "#74757c",
        "on-secondary": "#001b55",
        "surface-container": "#0a0a1a",
        "tertiary-fixed-dim": "#ff7986",
        "surface-container-low": "#050510",
        "surface-variant": "#111122",
        "inverse-surface": "#f9f9ff",
        "primary-container": "#c284ff",
        "secondary": "#7799ff",
        "outline-variant": "#46484e",
        "tertiary-dim": "#ff6f7e"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
