/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  // Always dark — no toggle.
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#cfdef7",
        "on-surface-variant": "#aaabaf",
        "tertiary-dim": "#8596ff",
        "primary-fixed": "#00eefc",
        "error-container": "#9f0519",
        "tertiary": "#97a5ff",
        "secondary": "#cfdef7",
        "tertiary-fixed-dim": "#8c9cff",
        "surface-bright": "#292c31",
        "error-dim": "#d7383b",
        "on-primary-container": "#005359",
        "surface-container-low": "#111417",
        "outline-variant": "#46484b",
        "surface-variant": "#23262a",
        "on-surface": "#f9f9fd",
        "surface-container-highest": "#23262a",
        "background": "#0c0e11",
        "primary-fixed-dim": "#00deec",
        "on-error": "#490006",
        "inverse-surface": "#f9f9fd",
        "surface-container-lowest": "#000000",
        "on-primary": "#005d63",
        "inverse-on-surface": "#535559",
        "on-secondary-container": "#c3d1ea",
        "tertiary-container": "#8596ff",
        "surface-container": "#171a1d",
        "secondary-dim": "#c1d0e8",
        "secondary-fixed-dim": "#c1d0e8",
        "surface-dim": "#0c0e11",
        "on-tertiary-fixed": "#000d52",
        "tertiary-fixed": "#9eabff",
        "inverse-primary": "#006a71",
        "surface-container-high": "#1d2024",
        "on-error-container": "#ffa8a3",
        "on-primary-fixed": "#003f43",
        "on-tertiary-fixed-variant": "#182d92",
        "primary-dim": "#00deec",
        "on-secondary": "#414f63",
        "on-tertiary": "#001c86",
        "outline": "#747579",
        "primary": "#8ff5ff",
        "on-tertiary-container": "#001367",
        "on-background": "#f9f9fd",
        "secondary-container": "#3a485b",
        "primary-container": "#00eefc",
        "on-secondary-fixed-variant": "#4b596d",
        "on-secondary-fixed": "#2f3d50",
        "on-primary-fixed-variant": "#005e64",
        "surface": "#0c0e11",
        "error": "#ff716c",
        "surface-tint": "#8ff5ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      transitionTimingFunction: {
        "out-expo": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
